/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymbolsRouteImport } from './routes/symbols'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as BrokerRouteImport } from './routes/broker'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as IndexRouteImport } from './routes/index'

const SymbolsRoute = SymbolsRouteImport.update({
  id: '/symbols',
  path: '/symbols',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRoute = BrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/broker': typeof BrokerRoute
  '/mentor': typeof MentorRoute
  '/symbols': typeof SymbolsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/broker': typeof BrokerRoute
  '/mentor': typeof MentorRoute
  '/symbols': typeof SymbolsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzer': typeof AnalyzerRoute
  '/broker': typeof BrokerRoute
  '/mentor': typeof MentorRoute
  '/symbols': typeof SymbolsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analyzer' | '/broker' | '/mentor' | '/symbols'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyzer' | '/broker' | '/mentor' | '/symbols'
  id: '__root__' | '/' | '/analyzer' | '/broker' | '/mentor' | '/symbols'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzerRoute: typeof AnalyzerRoute
  BrokerRoute: typeof BrokerRoute
  MentorRoute: typeof MentorRoute
  SymbolsRoute: typeof SymbolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symbols': {
      id: '/symbols'
      path: '/symbols'
      fullPath: '/symbols'
      preLoaderRoute: typeof SymbolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzerRoute: AnalyzerRoute,
  BrokerRoute: BrokerRoute,
  MentorRoute: MentorRoute,
  SymbolsRoute: SymbolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
